#My custom aliases
alias ll="ls -arlFh --color=auto"
alias l="ls -arlFh --color=auto"
alias follow"=tail -f -n 40"
alias f="tail -f -n 40"
alias dog="cat"
alias please="sudo"
alias speed="speedtest-cli"
alias ..="cd .."
alias df="df -H"
alias du="du -ch"
alias home="cd ~"
alias c="clear"
alias cls="clear"
alias smbreloadconfig="smbcontrol smbd reload-config"

